### ISSUE TITLE
docker nginx reverse proxy + goaccess container

### ISSUE THREAD

**Issue by AndreaHasani** [allinurl/goaccess#1297]
I can't seem to get this working.

Here's an example of my config

Nginx

	listen              443 ssl http2;
	location /ws/ {
	    proxy_pass http://localhost:7890;
	    proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection "Upgrade";
	}

```
goaccess.conf

port 7890
addr 0.0.0.0
ws-url wss://tld.com:443/ws/

```

```
Docket Compose

    nginx:
        restart: always
        image: nginx:stable-alpine
        links:
          - novelepubs:uwsgi
          - andreahasani:uwsgi1
          - tubex69:uwsgi2

        ports:
          - 80:80
          - 443:443


        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt

            # Logs server
            - ./containers/logger/nginx:/var/log/nginx
            - ./containers/logger/goaccess/html:/srv/stats

        networks:
            - websiteNetwork
     

    logger:
      restart: always
      image: allinurl/goaccess
      ports:
        - 7890:7890

      depends_on:
        - "nginx"

      volumes:
        - ./containers/logger/goaccess/data:/srv/data/
        - ./containers/logger/goaccess/html:/srv/report/
        - ./containers/logger/nginx:/srv/logs/
        - /etc/letsencrypt/:/etc/letsencrypt
      networks:
          - websiteNetwork


networks:
    websiteNetwork:
        driver: "bridge"

```
Am I doing something wrong?
