### ISSUE TITLE
Real time access logs from both access log files and access log archives

### ISSUE THREAD

**Issue by atymkiv** [allinurl/goaccess#1890]
I have nginx server producing logs: 1 access.log file per day. Old access logs files are being zipped. But I need to have statistic based on long period so I need to parse both access.log files and access.log.*.bz archives. 
Is there a way to do this?  
I've tried doing sth like this: `{ cat /var/log/nginx/access.log.1 ; zcat --force /var/log/nginx/access.log.* ; }| goaccess /var/log/nginx/access.log -o var/www/html/report.html --log-format=COMBINED --real-time-html -`. 
It works fine. 
but I can't manage to do the same with docker.
```
goaccess:
    image: allinurl/goaccess
    ports:
      - 7890:7890
    volumes:
      - /srv/goaccess:/goaccess
      - /var/www/report/index.html:/goaccess/index.html
      - /var/log/nginx:/goaccess/logs
    command: { cat /goaccess/logs/access.log.* ; zcat --force /goaccess/logs/access.log.*.bz ; }| goaccess /goaccess/logs/access.log --no-global-config --config-file=/goaccess/data/goaccess.conf -
```

goaccess.conf:
```
log-format COMBINED
output /goaccess/index.html
real-time-html true
```
