### ISSUE TITLE
Remove CMD from Dockerfile

### ISSUE THREAD

**Issue by Byh0ki** [allinurl/goaccess#1959]
Hello,

I'm currently using your docker image and I would like to know why you included the line: https://github.com/allinurl/goaccess/blob/7d231a24077a042d8aa112b5a48d082aeb5f76be/Dockerfile#L33 in the Dockerfile ?

I use docker-compose to deploy goaccess. The file look like this:
```
services:
  goaccess:
    image: allinurl/goaccess:1.4.1
    command: ["/var/log/nginx/access.log" ]
    volumes:
      - ./goaccess/goaccess.conf:/etc/goaccess/goaccess.conf
      - ./goaccess/report:/goaccess/report
      - ./logs/nginx-proxy:/var/log/nginx:ro
    expose:
      - "7890"
```

I have to add the line: `command: ["/var/log/nginx/access.log" ]` because I need to overwrite the command statement (`--help`) from the Dockerfile. My goaccess.conf is already specifying the log file so this is kinda redundant and I didn't find a way to remove the statement. (I can't use `command: [""]` because it will give an empty string to goaccess which will fail to parse the corresponding log because the filename is empty).

I can open a PR with a fix and a rewrite of the corresponding doc if you want :)

Thanks for your work on goaccess !
