### ISSUE TITLE
Token '16/Jan/2021' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by lari002** [allinurl/goaccess#1999]
Would you please help me with this error? I am doubtful this is a bug but as I learned goaccess' errors could be a bit misleading. I am running a goaccess container in a kubernetes cluster like this:

```
...
      containers:
      - image: allinurl/goaccess        
        name: goaccess
        args: 
          - -f
          - /logs/access_log.log
          - --log-format='%h %^ %^ [%d:%t] "%r" %s %b "%R" "%u"
          - -o
          - /report/report.html
          - --time-format='%H:%M:%S %z'
          - --date-format='%d/%b/%Y'
          - --no-global-config
          - --real-time-html
...
```

access log:
```
127.0.0.1 - - [16/Jan/2021:07:38:07 -0500] "GET / HTTP/1.1" 302 - "-" "curl/7.61.1"
127.0.0.1 - - [16/Jan/2021:07:38:11 -0500] "GET / HTTP/1.1" 302 - "-" "curl/7.61.1"

```

goaccess output:
```
 [PARSING /logs/access_log.log] {0} @ {0/s}
==1== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==1== https://goaccess.io - <hello@goaccess.io>
==1== Released under the MIT License.
==1==
==1== FILE: /logs/access_log.log
==1== Parsed 2 lines producing the following errors:
==1==
==1== Token '16/Jan/2021' doesn't match specifier '%d'
==1== Token '16/Jan/2021' doesn't match specifier '%d'
==1==
==1== Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
Looks like your locale is not set to English but your access log is showing English dates. You can run it as 

    LC_TIME="en_US.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'

**Comment by lari002** [comment]
No it's set. I should have included the whole manifest for it. You can see there that LANG and LC_TIME are set.

```
containers:
      - image: allinurl/goaccess        
        name: drd-goaccess
        resources: 
          limits:
            memory: 100Mi
            cpu: 100m        
        args: 
          - -f
          - /logs/access_log.log
          - --log-format='%h %^ %^ [%d:%t] "%r" %s %b "%R" "%u"
          - -o
          - /report/report.html
          - --time-format='%H:%M:%S %z'
          - --date-format='%d/%b/%Y'
          - --no-global-config
          - --real-time-html
        env:
          - name: LANG
            value: "en_US.UTF-8"
          - name: LC_TIME
            value: "en_US.UTF-8"
        ports:
        - containerPort: 7890
        volumeMounts:
          - mountPath: /report
            name: report
          - mountPath: /logs
            name: accesslog
```
