### ISSUE TITLE
Prebuilt docker image error

### ISSUE THREAD

**Issue by landcraft** [allinurl/goaccess#2153]
I'm trying to use your prebuilt docker image, but whenever I run it, it just shows help then stops. I also noticed that the init says ```/bin/goaccess --help```

Can you help?

**Comment by allinurl** [comment]
Have you tried running it as indicated [**here**](https://github.com/allinurl/goaccess#docker)?

**Comment by landcraft** [comment]
I've used another image, and that one works, so I guess I can close this.

**Comment by olonsoft** [comment]
I have the same problem here.
I am using Caddy server.
The docker-compose runs but shows only the (commands) help.
`docker-compose.yml` in folder: `goaccess` : 

```yaml
version: "3.8"
services:
  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: unless-stopped
    ports:
      - 7890:7890
    volumes:
      - ./data:/goaccess
      - ~/www/goaccess/index.html:/goaccess/index.html
      - ~/docker/caddy/log/access.log:/goaccess/access.log:ro
```

in `data/goaccess.conf` :

```
log-format CADDY
log-file /goaccess/access.log
output /goaccess/index.html
real-time-html true
```

create the file

`sudo touch ~/www/goaccess/index.html`

then start the container but only the help is shown.

If I run
 `cat~/docker/caddy/log/access.log | docker run --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --log-format CADDY - > report.html`
the `report.html` is successfully being created.

Is something wrong with the paths?
Also I think that you must edit the page <https://github.com/allinurl/goaccess/blob/master/DOCKER.md> because it mentions that the docker container doesn't use subfolders `/srv/{data,html,logs}` anymore. But some code examples there, already use `/srv/{data,html,logs}`

@landcraft what image did you use?
