### ISSUE TITLE
Error occurred at: src/settings.c - get_config_file_path - 137

### ISSUE THREAD

**Issue by morganzero** [allinurl/goaccess#2165]
Hi there,
I'm new to **goaccess**, I have been reading up on how others have set this up, and I think I got most parts right. Below is the error I'm getting when setting up the docker container, followed by my config and docker-compose.

I'm sure I'm missing something on my end. I would highly appreciate some pinpointers to get me on the right path of fixing this.

Cheers!

**The Error**
```
GoAccess - version 1.5.1 - Aug 15 2021 18:56:19
Config file: /logs/goaccess.conf

Fatal error has occurred
Error occurred at: src/settings.c - get_config_file_path - 137
Unable to open the specified config file. No such file or directory
```
**My compose**
```
  goaccess:
    image: allinurl/goaccess
    restart: unless-stopped
    container_name: goaccess
    command: ["/logs/access.log", "-a", "-o html", "--no-global-config", "--config-file=/logs/goaccess.conf",
          "--ws-url=wss://ws.${DOMAIN}:443", "-"]
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7899:7890"
    volumes:
      - /opt/appdata/goaccess/data:/data
      - /opt/appdata/goaccess/logs:/logs
      - /opt/appdata/goaccess/report:/report
      - /opt/appdata/goaccess/geoIp/GeoLite2-City.mmdb:/GeoLite2-City.mmdb
      - /opt/appdata/goaccess/goaccess.conf:/goaccess.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/appdata/traefik/data/logs/access.log:/logs/access.log:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goaccess.entrypoints=http"
      - "traefik.http.routers.goaccess.rule=Host(`goaccess.${DOMAIN}`)"
      - "traefik.http.middlewares.goaccess-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.goaccess.middlewares=https-redirect@file,secured@file"
      - "traefik.http.routers.goaccess-secure.middlewares=oauth"
      - "traefik.http.routers.goaccess-secure.entrypoints=https"
      - "traefik.http.routers.goaccess-secure.rule=Host(`goaccess.${DOMAIN}`)"
      - "traefik.http.routers.goaccess-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.goaccess.loadbalancer.server.port=7890"
```
**The config**
```
log-file /logs/access.log
output /index.html
real-time-html true
daemonize false
log-format COMMON
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ "%v" %^ %T
time-format %T
date-format %d/%b/%Y
anonymize-ip false
ws-url wss://*.REDACTED.com:443/ws
geoip-database /GeoLite2-City.mmdb
```
