### ISSUE TITLE
No input data was provided nor there's data to restore

### ISSUE THREAD

**Issue by samcro1967** [allinurl/goaccess#2169]
Trying to setup a conf file.   I can run it from the cli with no issue with all options specified, but the same options in the conf file return "No time format was found on your conf file".  Not sure what I am doing wrong.
```
cat access.log | docker run --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --log-format CADDY - > index.html
```
It is not working with goaccess.conf.
```
docker run --rm -i -e LANG=$LANG allinurl/goaccess -a

GoAccess - version 1.5.1 - Aug 15 2021 18:56:11
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1459
No input data was provided nor there's data to restore.
```

**goaccess.conf**
```
config-file /etc/goaccess/goaccess.conf
log-format CADDY
log-file /goaccess/access.log
output /goaccess/index.html
real-time-html true
```

**docker-compose**
```
  goaccess:
    hostname: goaccess
    image: allinurl/goaccess
    container_name: goaccess
    ports:
      - 7890:7890
    volumes:
      - "${docker}/goaccess:/goaccess"
      - "${docker}/goaccess/index.html:/goaccess/index.html"
      - "${docker}/goaccess/goaccess.conf:/etc/goaccess/goaccess.conf"
      - "${docker}/caddy2/data/access.log:/goaccess/access.log:ro"
```
