### ISSUE TITLE
Docker-compose: Parsed but still unable to fread the specific log file 'goaccess'

### ISSUE THREAD

**Issue by renegadevi** [allinurl/goaccess#2247]
GoAccess seem to find and parse the log with >34k entries, but then gives a fatal error because it's unable to "**fread**" a log file 'goaccess'?

I found a previous issue (https://github.com/allinurl/goaccess/issues/2023) which had the issue of not even parsing the log, but even with the correct path for, it's still error's out after it's been parsed?

docker-compose.yml snippet
```yaml
...
nginx:
    ...
    volumes:
      - ./services/web:/home/app/web
      - ./services/web/app/static:/home/app/web/app/static
      - ./services/nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always

goaccess:
    image: allinurl/goaccess:latest
    ports:
      - 7890:7890
    volumes:
      - ./services/nginx/logs:/opt/log
      - ./services/goaccess:/goaccess
      - ./services/goaccess/html/index.html:/html/index.html
    command: ["goaccess", "--no-global-config", "--config-file=/goaccess/goaccess.conf"]
    depends_on:
      - nginx
...
```

goaccess.conf
```
log-file /opt/log/access.log
output /html/index.html
```

output
```
[PARSING /opt/log/access.log] {34729} @ {34729/s}
GoAccess - version 1.5.3 - Dec 12 2021 01:13:22
Config file: /goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - set_initial_persisted_data - 1964
Unable to fread the specified log file 'goaccess'

exit code: 1
```
