### ISSUE TITLE
docker-compose - reading gz logs + normal logs?

### ISSUE THREAD

**Issue by rwjack** [allinurl/goaccess#2333]
Hello,

I'm trying to read `.gz` and regular traefik logs while running goaccess inside docker-compose, but I can't seem to figure out a way to accomplish this.

`docker-compose.yml`
```
version: "3"

volumes:
  data:
  report:

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped

    container_name: goaccess-nginx
    hostname: goaccess-nginx

    ports:
      - "10000:80"

    volumes:
      - report:/usr/share/nginx/html:ro

    depends_on:
      - goaccess

  goaccess:
    image: allinurl/goaccess:latest
    restart: unless-stopped
    entrypoint: sh
    command: -c 'zcat /srv/traefik-logs/access.log.*.gz | goaccess -'
    #command: -f /srv/traefik-logs/access.log

    container_name: goaccess
    hostname: goaccess

    volumes:
      - ./goaccess.conf:/etc/goaccess/goaccess.conf:ro
      - /mnt/traefik-logs/:/srv/traefik-logs/:ro
      - data:/srv/data
      - report:/srv/report
```
So the idea is -
- First import gz logs with the current docker-compose layout
- And then run only with the second command field (without entrypoint and first command), so goaccess reads existing gz logs and then stays online reading the actual logs.

`goaccess.conf`:
```
origin https://local.domain
ws-url wss://local.domain:443/live
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ "%v" "%^" %Tms
date-format %d/%b/%Y
time-format %T
output /srv/report/index.html
db-path /srv/data
persist true
restore true
real-time-html true
```

Doing the following commands on my debian desktop gives me 2M total requests. First command yields 1.1M, the second one adds another 0.9M. 
```
zcat logs/access.log.*.gz | goaccess -p ./goaccess.conf -
goaccess -p ./goaccess.conf -f logs/access.log
```
This doesn't make sense for the following reason - All logs should be around 5.69M requests. Unfortunately when goaccess parses only `.gz` logs (first command), the number of requests shown on the output report is 1.1M. Strangely when I do the second command, which should only parse `access.log`, it adds another 0.9M, instead of 0.57M - Which is the actual amount of requests in `access.log`

![image](https://user-images.githubusercontent.com/59068073/171735653-c8feb9ae-60d8-4597-af57-e69873752688.png)

Commenting out `#real-time-html true`, parses the gz logs correctly for some reason: (5.7M)

![image](https://user-images.githubusercontent.com/59068073/171736408-a01c0f00-6015-4cb1-97b2-3a24a89af6fd.png)

Yeah and same for the regular `access.log` (0.57M)

![image](https://user-images.githubusercontent.com/59068073/171736815-1c230d01-24d5-4066-b434-62b56c39001f.png)

**Man, fuck this flag I'm legit busting my balls for the past 6 hours testing and documenting all this just for it to work now. Fuck.**

Running `docker-compose up -d` with the first command (which should yield the same output as on my host) only parses 79k requests, which makes absolutely 0 sense. You'd think it perhaps parsed a single log, but that doesn't seem to be the case.
![image](https://user-images.githubusercontent.com/59068073/171732893-b3a34447-898c-466d-b5ff-d46179187d19.png)

All in all, I'm simply trying to read week old logs which are in gz format, just to save them to the goaccess db, and after that keep goaccess running as a container and keep parsing logs from `access.log` regularly, though I also don't understand how often does it automatically re-parse the current file for updates?

And also, how would this be best implemented with `logrotate`, since `access.log` rotates daily. Perhaps force an `access.log` parse before rotating?

**Comment by rwjack** [comment]
Workaround:

`docker-compose.yml`
```
  goaccess:
    image: allinurl/goaccess
    restart: unless-stopped
    entrypoint: /entrypoint.sh

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./read.sh:/read.sh:ro
      - ./conf:/srv/conf:ro
      - /mnt/traefik-logs/:/srv/traefik-logs/:ro
      - data:/srv/data
      - report:/srv/report
```

`entrypoint.sh`
```
#!/usr/bin/env sh

sh read.sh | egrep -v "whatever|filtering|you|want" | goaccess -p /srv/conf/default.conf --db-path /srv/data/global -o /srv/report/global/index.html  -

sleep 15m
```

`read.sh`
```
#!/usr/bin/env sh

for file in /srv/traefik-logs/*; do
    if [ $(basename "$file") == "access.log" ]; then
        cat "$file"
    else
        zcat "$file"
    fi
done
```

**Comment by allinurl** [comment]
Awesome, thanks a lot for sharing those findings.

**Comment by rwjack** [comment]
Hey, this does not work as I expected it to. It keeps accumulating logs and adding them together, instead of skipping ones already added.

Eg.
access.log - 5 requests
access.log.1.gz - 10 requests
delete all db files -> run container -> report says: 15 total requests (as it should be)

When this container entrypoint.sh runs again in 24 hours: 30 requests
When this container entrypoint.sh runs again in 48 hours: 45 requests
^ If we take the assumption that no logs were made in these 48 hours ^

Not sure if I'm explaining this correctly, but it seems I'm somehow just compounding everything instead of ignoring existing logs in the db.

**Comment by rwjack** [comment]
And something seems very odd, since I'm doing it like this, and it just keeps incrementing the logs every time it runs (every 30 seconds for about ~+2500 requests), which makes no sense since the logs are test files which don't change in content.

docker-compose.yml:
```yaml
 goaccess:
    image: allinurl/goaccess:latest
    restart: unless-stopped
    entrypoint: /entrypoint.sh

    container_name: goaccess-test
    hostname: goaccess-test

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./read.sh:/read.sh:ro
      - ./conf:/srv/conf:ro
      - /mnt/traefik-logs/:/srv/traefik-logs/:ro
      - data-test:/srv/data
      - report-test:/srv/report
```



global.conf:
```
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ "%v" "%^" %Tms
date-format %d/%b/%Y
time-format %T

persist true
restore true

keep-last 2
hour-spec min
```

read.sh:
```shell
#!/usr/bin/env sh

cat /srv/traefik-logs/test.log

zcat /srv/traefik-logs/test.log.1.gz
```

entrypoint.sh:
```shell
#!/bin/sh

for service in global; do
    if [ ! -d /srv/data/$service ]; then
        mkdir /srv/data/$service
    fi

    if [ ! -d /srv/report/$service ]; then
        mkdir /srv/report/$service
    fi


    case $service in
        global)
            sh read.sh | goaccess -p /srv/conf/default.conf --db-path /srv/data/global -o /srv/report/global/index.html  -
            ;;

    esac
done

sleep 30s
```

**Comment by rwjack** [comment]
So a simplified version of what I'm looking for is:

```
zcat access.log.*.gz | goaccess # create the report from all logs

cat access.log | goaccess --real-time-html # and continue reading from the active access.log, and append to the same db
```

Is this doable?

**Comment by rwjack** [comment]
I can't seem to figure out a way to juggle gz + regular files, without missing something in the report.

If I first read all gz files and persist them,
and then `tail -f` and restore+persist the access.log file,
Then the final report misses 100% of the access.log file, minus 10 lines of the `tail -f` command, excluding all future output.

If I first read all gz files + access.log and persist them
and then `tail -f` and restore+persist the access.log file,
Then the final report has duplicate 10 log entries of the `tail -f` command

Ah, so while writing this a solution came to my mind:
If I first read all gz files + access.log and persist them
and then `tail -f -n0` and restore+persist the access.log file,
I should have a report with non duplicate entries, and continued live reporting?

**Comment by rwjack** [comment]
Ugh, I busted my balls, but this might be a decent solution:

docker-compose.yml:
```yaml
version: "3"

volumes:
  data:
  report:
  dangling-volume:

services:
  goaccess:
    image: allinurl/goaccess:latest
    restart: unless-stopped
    entrypoint: /entrypoint.sh

    container_name: goaccess
    hostname: goaccess

    ports:
      - "20000:20000"
      - "20001:20001"
      # etc...

    volumes:
      - ./read.sh:/read.sh:ro
      - ./conf:/srv/conf:ro
      - /traefik-logs/:/srv/traefik-logs/:ro
      - data:/srv/data
      - report:/srv/report
      - dangling-volume:/var/www/goaccess
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
```

read.sh:
```shell
#!/usr/bin/env sh

#for file in $(find "$log_dir" -type f -name "access.log.*.gz" -printf "%T+\t%p\n" | sort | awk '{print $2}'); do # no -printf on busybox wtf
for file in $(find "$log_dir" -type f -name "access.log*.gz" -exec stat -c "%Y %n" {} \; | sort | awk '{print $2}'); do
    zcat "$file"
done

cat "$log_dir"/access.log
```

entrypoint.sh:
```shell
#!/bin/sh

## find out how to persist gz logs and continue reading new ones
# first read gz, persist
# then restore+persist with tail -n0 regular log file

export db_dir="/srv/data"
export report_dir="/srv/report"
export conf_dir="/srv/conf"
export log_dir="/srv/traefik-logs"
initialize=0

#sleep 1h

query_logs () {
    local service=$1
    local config=$2
    local query=$3

    echo "$(date +"[%Y-%m-%d %H:%M:%S]") [*] Initializing $service: $config config: query - \"$query\""

    if [ -z "$query" ]; then
        sh /read.sh | goaccess \
            --config-file=$conf_dir/$config.conf \
            --db-path=$db_dir/$service \
            --output=$report_dir/$service/index.html - > /dev/null 2>&1
    else
        sh /read.sh | egrep "$query" | goaccess \
           --config-file=$conf_dir/$config.conf \
           --db-path=$db_dir/$service \
           --output=$report_dir/$service/index.html - > /dev/null 2>&1
    fi

    initialize=0
}

start_live_query() {
    local service=$1
    local config=$2
    local query=$3
    local port=$4
    localdomain=your.domain

    echo "$(date +"[%Y-%m-%d %H:%M:%S]") [*] Starting WSS for $service, on port $port"
    echo

    if [ -z "$query" ]; then
        tail -f -n0 $log_dir/access.log | goaccess \
            --ws-url=wss://$service.$localdomain:443 --port=$port --real-time-html --restore \
            --config-file=$conf_dir/$config.conf \
            --db-path=$db_dir/$service \
            --output=$report_dir/$service/index.html - > /dev/null 2>&1 &
    else
        tail -f -n0 $log_dir/access.log | egrep "$query" | goaccess \
           --ws-url=wss://$service.$localdomain:443 --port=$port --real-time-html --restore \
           --config-file=$conf_dir/$config.conf \
           --db-path=$db_dir/$service \
           --output=$report_dir/$service/index.html - > /dev/null 2>&1 &
    fi

}


for service in global service1; do # service2 etc....
    echo "$(date +"[%Y-%m-%d %H:%M:%S]")  [+] Configuring $service"

    if [ ! -d "$db_dir"/$service ]; then
        echo "$(date +"[%Y-%m-%d %H:%M:%S]") [*] Didn't find "$db_dir"/$service. Creating..."
        mkdir "$db_dir"/$service
        initialize=1
    fi

    if [ ! -d "$report_dir"/$service ]; then
        echo "$(date +"[%Y-%m-%d %H:%M:%S]") [*] Didn't find "$report_dir"/$service. Creating..."
        mkdir "$report_dir"/$service
        initialize=1
    fi

    # if the container was down, there will be missed logs since dirs exist
    # and the container missed to live parse/save actual logs, that is okay because it won't change the statistics much

    # a clean run will fix those ^ issues, maybe once a month backup/delete volumes and restart the stack?


    case "$service" in
        global)
            if [ "$initialize" -eq 1 ]; then
                query_logs $service global ""
            fi

            start_live_query $service global "" 20000
            ;;
        service1)
            if [ "$initialize" -eq 1 ]; then
                query_logs $service default "traefik-router-query-for-service-1"
            fi

            start_live_query $service default "traefik-router-query-for-service-1" 20001
            ;;
        #service2)
        #;; # etc....
    esac

done

echo "$(date +"[%Y-%m-%d %H:%M:%S]") [+] All done, now sleeping till the end of time.."
sleep infinity
```
