### ISSUE TITLE
Real-time html not work because wss request not return 0 bytes always

### ISSUE THREAD

**Issue by emrancu** [allinurl/goaccess#2496]
Hello ,
I run geoaccess real-time- html report and server with a subdomain but real time tata sync is not work because wss request return nothing. 

I am trying 'GeoAccess' in ubuntu with caddy server. 

please help me. Thanks you so much ❤️🙏

I run following command:
``` goaccess /var/log/caddy/ezytor.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://log.besnik.net:443/ws --port=9871```

And here is the caddy block:

```
 log.besnik.net {
    root * /var/www/goaccess

        # Enable the static file server.
        file_server

  reverse_proxy /ws localhost:7891
}  

```

Here the output of wss request:

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/11002290/229300786-5987bcbf-ba4b-4292-aa53-aeee5f5b58f7.png">

Here is the request Info:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/11002290/229301072-62d1db2b-053e-48af-8128-21df226d1cf9.png">

**Comment by allinurl** [comment]
Two things at the first glance:

1. Please try the latest version, v1.7.2 fixed some issues with --ws-url.
2. You passed `--port=9871`  but your reverse proxy is `localhost:7891`. 

Let me know if that helps.

**Comment by emrancu** [comment]
@allinurl Thank you 🙏

It's working after upgrading GoAccess❤️ version.

**Comment by emrancu** [comment]
Hello @allinurl 
I am trying to run with Docker but unable. show error like:

```
Attaching to goaccess-log-viewer_goaccess_1
goaccess_1  |  [SETTING UP STORAGE goaccess /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871] {0} @ {0/s}
goaccess_1  | GoAccess - version 1.7.1 - Mar  1 2023 01:28:02
goaccess_1  | Config file: /etc/goaccess/goaccess.conf
goaccess_1  |
goaccess_1  | Fatal error has occurred
goaccess_1  | Error occurred at: src/parser.c - parse_log - 2189
goaccess_1  | No time format was found on your conf file.
goaccess_1  |
```

My docker-compose.yml

```
version: '3'
services:
  goaccess:
    image: allinurl/goaccess:latest
    volumes:
      - /var/log/caddy:/var/log/caddy
      - /var/www/goaccess:/var/www/goaccess
    ports:
      - 9871:9871
    command: bash -c "goaccess /var/log/caddy/ezytor.access.log /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871"

```
