### ISSUE TITLE
Unable to run GoAccess with docker-compose.yml

### ISSUE THREAD

**Issue by emrancu** [allinurl/goaccess#2498]
Hello @allinurl 
I am trying to run with Docker but unable. show error like:

```
Attaching to goaccess-log-viewer_goaccess_1
goaccess_1  |  [SETTING UP STORAGE goaccess /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871] {0} @ {0/s}
goaccess_1  | GoAccess - version 1.7.1 - Mar  1 2023 01:28:02
goaccess_1  | Config file: /etc/goaccess/goaccess.conf
goaccess_1  |
goaccess_1  | Fatal error has occurred
goaccess_1  | Error occurred at: src/parser.c - parse_log - 2189
goaccess_1  | No time format was found on your conf file.
goaccess_1  |
```

My docker-compose.yml

```
version: '3'
services:
  goaccess:
    image: allinurl/goaccess:latest
    volumes:
      - /var/log/caddy:/var/log/caddy
      - /var/www/goaccess:/var/www/goaccess
    ports:
      - 9871:9871
    command: bash -c "goaccess /var/log/caddy/ezytor.access.log /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871"

```

_Originally posted by @emrancu in https://github.com/allinurl/goaccess/issues/2496#issuecomment-1493185008_

**Comment by emrancu** [comment]
it's work Nicely with Docker. 

Updated docker-compose.yml:

```
version: '3'
services:
  goaccess:
    image: allinurl/goaccess:latest
    volumes:
      - "/var/log/caddy:/var/log/caddy:ro"
      - "/var/www/goaccess:/var/www/goaccess:rw"
    ports:
      - "9871:9871"
    command: "/var/log/caddy/ezytor.access.log /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871"

```
