### ISSUE TITLE
"Static Requests" panel empty in 1.8.1

### ISSUE THREAD

**Issue by xrstf** [allinurl/goaccess#2618]
I just upgraded my Goaccess container from 1.8 to 1.8.1 and suddenly the static requests panel stays empty. All other panels load fine and show proper data, the websocket connection is also working fine. The console in Firefox shows no errors. The goaccess server is also not logging anything.

I run Goaccess via Docker, making it ingest an nginx log:

```yaml
version: "3.8"

services:
  goaccess:
    image: allinurl/goaccess:1.8.1
    restart: unless-stopped
    command:
      - --agent-list
      - --real-time-html
      - --config-file=/zoidberg/etc/goaccess/mysite.conf
      - --db-path=/zoidberg/var/goaccess/mysite
      - --persist
    volumes:
      - "/etc/goaccess:/zoidberg/etc/goaccess:ro"
      - "/srv/www:/zoidberg/srv/www"
      - "/var/log:/zoidberg/var/log"
      - "/var/goaccess:/zoidberg/var/goaccess"
    networks:
      - nginx_nginx
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
```

And my config is

```
# example goaccess conf file for gopanel
# edit site1 values and change title to suit
html-report-title mysite

# the logs you want to process
log-format COMBINED
log-file /zoidberg/var/log/nginx/mysite-access.log

# the location you will host from
output-format /zoidberg/srv/www/stats.mysite/index.html
ws-url stats.mysite:443/wss

# other options as you prefer
#ignore-crawlers true
#hide-referrer example.com
```
