### ISSUE TITLE
Counters overlaps in parsing progress output

### ISSUE THREAD

**Issue by rc5hack** [allinurl/goaccess#2637]
While parsing big (5kk lines, 1Gb+) logfile, counters in progress output overlaps each other:

```
 [PARSING /path/to/file.log] {413696} @ {17237/s}d] {0} @ {0/s}
 [PARSING /path/to/file.log] {836023} @ {17787/s}
 [PARSING /path/to/file.log] {1234948} @ {17393/s}
 [PARSING /path/to/file.log] {1623040} @ {17266/s}
 [PARSING /path/to/file.log] {1987584} @ {16843/s}
 [PARSING /path/to/file.log] {2343602} @ {16621/s}
 [PARSING /path/to/file.log] {2703367} @ {16377/s}
 [PARSING /path/to/file.log] {3066806} @ {16302/s}
 [PARSING /path/to/file.log] {3433472} @ {16188/s}
 [PARSING /path/to/file.log] {3821895} @ {16263/s}
 [PARSING /path/to/file.log] {4206259} @ {16240/s}
 [PARSING /path/to/file.log] {4574208} @ {16220/s}@ {16245/s}
 [PARSING /path/to/file.log] {4954409} @ {16243/s}6225/s}
 [PARSING /path/to/file.log] {5348178} @ {16255/s}/s}
 [PARSING /path/to/file.log] {5660451} @ {16265/s}
WebSocket server ready to accept new client connections
```
Looks like there are more lines that shown, and they are competing some way 🤷🏻‍♂️

I can reproduce this problem in versions 1.8.1 and 1.9.1.

Running `goaccess` with `docker compose`, with the following config:

```yml
version: '2.4'
services:
   goaccess:
    container_name: goaccess
    image: allinurl/goaccess:1.9.1
    volumes:
      - ./geodb:/opt/geodb/:ro
      - ./www/:/opt/www/:rw
      - /path/to/logs/:/opt/logs/:ro
    command:
      - /opt/logs/file.log
      - --geoip-database=/opt/geodb/GeoLite2-City.mmdb
      - --agent-list
      - --with-output-resolver
      - --real-time-html
      - --html-refresh=1
      - --log-format=VCOMBINED
      - --output=/opt/www/index.html
      - --html-report-title=logs analysis
      - --ws-url=wss://${DOMAIN_NAME}:443/ws
      - --origin=https://${DOMAIN_NAME}
      - --enable-panel=VISITORS
      - --enable-panel=REQUESTS
      - --enable-panel=REQUESTS_STATIC
      - --enable-panel=NOT_FOUND
      - --enable-panel=HOSTS
      - --enable-panel=OS
      - --enable-panel=BROWSERS
      - --enable-panel=VISIT_TIMES
      - --enable-panel=VIRTUAL_HOSTS
      - --enable-panel=REFERRERS
      - --enable-panel=REFERRING_SITES
      - --enable-panel=KEYPHRASES
      - --enable-panel=STATUS_CODES
      - --enable-panel=REMOTE_USER
      - --enable-panel=GEO_LOCATION
      - --html-prefs={"theme":"darkPurple","perPage":10,"layout":"vertical"}
    restart: unless-stopped
    cpus: 1.00
    mem_limit: 256m
```
