### ISSUE TITLE
Does goaccess respect docker mem_limit?

### ISSUE THREAD

**Issue by rc5hack** [allinurl/goaccess#2645]
When run with docker-compose, it seems that goaccess "knows" of `mem_limit` set on docker side:

configuration 1: `mem_limit: 384m`
```yaml
version: '2.4'
services:
   goaccess:
    image: allinurl/goaccess:1.9.1
    command:
      - /path/to/logs
      - --log-format=VCOMBINED
      - --output=/path/to/report.html
      - --real-time-html
      - --ws-url=wss://${DOMAIN_NAME}:443/ws
    environment:
      - GOMEMLIMIT=320MiB
    cpus: 1.00
    mem_limit: 384m
```

RAM consumption with configuration 1: `360m` (not great, not terrible)
```sh
docker stats --no-stream
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
fe7834d3e921   goaccess              0.01%     360.3MiB / 384MiB   93.82%    31.8kB / 1.43MB   92.4MB / 0B       4
```

configuration 2: all the same, but `mem_limit: 512m`
```yaml
version: '2.4'
services:
   goaccess:
    image: allinurl/goaccess:1.9.1
    command:
      - /path/to/logs
      - --log-format=VCOMBINED
      - --output=/path/to/report.html
      - --real-time-html
      - --ws-url=wss://${DOMAIN_NAME}:443/ws
    environment:
      - GOMEMLIMIT=320MiB
    cpus: 1.00
    mem_limit: 512m
```

RAM consumption with configuration 2: `401m` (even more than previous maximum limit?! how???)
```sh
docker stats --no-stream
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
7c048f6d8a92   goaccess              4.87%     401.2MiB / 512MiB   78.36%    98.1kB / 19.2MB   176MB / 0B        4
```

Thus, the higher `mem_limit` value becomes, the more RAM application consumes under identical conditions.

This behavior is strange, because `goaccess` remains the same and the logs it processes remain the same. It seems that `goaccess` somehow respect the `mem_limit` value and changes the behavior depending on it. This is usually not the case: applications running in Docker don't "know" about `mem_limit` value and don't respect it's changes out of the box.

Deleting `GOMEMLIMIT` variable changes practically nothing in this configurations.

Does `goaccess` intentionally respect docker `mem_limit` really?
