### ISSUE TITLE
Multiple logs being generated by NGINX proxy

### ISSUE THREAD

**Issue by huntson** [allinurl/goaccess#2776]
I've got a different log file being generated by each config of NGINX proxy as such:

access.log*               proxy-host-6_error.log*
default-host_access.log*  proxy-host-7_access.log*
default-host_error.log*   proxy-host-7_error.log*
fallback_access.log*      proxy-host-8_access.log*
fallback_error.log*       proxy-host-8_error.log*
proxy-host-3_access.log*  redirection-host-1_access.log*
proxy-host-3_error.log*   redirection-host-1_error.log*

Is there a way to deal with this in goaccess or does the NGINX config need to be modified somehow?

**Comment by allinurl** [comment]
You can grab all the access logs and pipe them straight into GoAccess, e.g.,

    cat access.log* proxy-host-6_error.log* default-host_access.log* proxy-host-7_access.log* default-host_error.log* proxy-host-7_error.log* fallback_access.log* proxy-host-8_access.log* fallback_error.log* proxy-host-8_error.log* proxy-host-3_access.log* redirection-host-1_access.log* proxy-host-3_error.log* redirection-host-1_error.log* | goaccess - -o report.html --log-format=COMBINED

or

    find . -type f -name 'access.log*' -o -name 'proxy-host-*-access.log*' -o -name 'default-host*_access.log*' -o -name 'fallback_access.log*' -o -name 'redirection-host-*-access.log*' | xargs cat | goaccess - -o report.html --log-format=COMBINED

**Comment by huntson** [comment]
The issue is that as I crate most hosts/proxies the number of logs increases.  Is there a way to honor any files with the dot log extension in a folder?

**Comment by allinurl** [comment]
If I understand correctly, you could try, e.g.:

    find . -type f -name '*.log*' ! -name '*error*' | xargs cat | goaccess - -o report.html --log-format=COMBINED

**Comment by huntson** [comment]
How/where does this get put in the config file as I'm running this as a Docker and need this in the config.

**Comment by allinurl** [comment]
find . -type f -name '*.log*' ! -name '*error*' | xargs cat | docker run --rm -i -v "$(pwd)/report.html:/report.html" -e LANG=$LANG allinurl/goaccess - -o /report.html --log-format=COMBINED

https://github.com/allinurl/goaccess?tab=readme-ov-file#docker

**Comment by huntson** [comment]
I don't think we're on the same page here.  I'm using Portainer to maintain a stack where this is the config:

`goaccess:
    image: gregyankovoy/goaccess
    container_name: goaccess
    ports:
      - "7889:7889"  
    environment:
      - PUID=1026 
      - PGID=100   
    volumes:
      - /share/ZFS20_DATA/docker/nginx-proxy/logs:/opt/log  
      - /share/ZFS20_DATA/docker/goaccess:/config  
'

I'm attempting to understand how to modify the config file in order to allow this to work within Portainer and not call the docker via CLI.

**Comment by allinurl** [comment]
I'm not very familiar with Portainer, but it seems you could try the following:

```
services:
  goaccess:
    image: gregyankovoy/goaccess
    container_name: goaccess
    ports:
      - "7889:7889"
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - /share/ZFS20_DATA/docker/nginx-proxy/logs:/opt/log  # Logs directory
      - /share/ZFS20_DATA/docker/goaccess:/config          # Config and output
    command: >
      /bin/sh -c "
      find /opt/log -type f -name '*.log*' ! -name '*error*' | 
      xargs cat | 
      goaccess - --real-time-html -o /config/report.html --log-format=COMBINED --daemonize"
```
